### ISSUE TITLE
Add Scope Constraint Optional Argument

### ISSUE THREAD

**Issue by mr-pmillz** [edoardottt/csprecon#171]
**Is your feature request related to a problem? Please describe.**
It would be a nice feature to optionally include a scope constraint by domain so that results are constrained to only subdomains of the specified constraint domain or a list of constraint domains in a file.

**Describe the solution you'd like**
When --scope example.com is specified, only return subdomains of *.example.com. Ex:
api.example.com
foobarbaz.example.com
etc...

**Describe alternatives you've considered**
I'd like to use this tool but currently too many third-party hosts are returned and it would be very useful to only get hosts that are in-scope for a penetration test that you're authorized to test.

**Additional context**
I could manually parse the output results to filter out-of-scope items but this would be a great feature to have built-in to the project.

**Comment by mr-pmillz** [comment]
Whoops! Nevermind, I totally missed this flag haha
```shell
-d, -domain string[]  Filter results belonging to these domains (comma separated)
```

perhaps could rename the -d --domain flag to scope, idk, closing issue 😅

**Comment by edoardottt** [comment]
No worries @mr-pmillz , if you have other suggestions just open other issues :)
