### ISSUE TITLE
Add Content-Security-Policy-Report-Only header check

### ISSUE THREAD

**Issue by edoardottt** [edoardottt/csprecon#279]
Add Content-Security-Policy-Report-Only header check

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy-Report-Only

**Comment by Er-Sadiq** [comment]
Hi , I'm Working on a Fix will soon raise a RP

**Comment by edoardottt** [comment]
Done (v0.4.0)
