### ISSUE TITLE
-d flag returns 0 results  always

### ISSUE THREAD

**Issue by kleozzy** [edoardottt/csprecon#291]
If i use the tool with -d it always returns 0 results.

echo domain | csprecon - works fine returning several subs

echo domain | csprecon -d domain - doesnt return anything , even after trying domains found above .

i have also tried with cat targets.txt | csprecon -d domain - also returns nothing.

**Comment by kleozzy** [comment]
I guess the reason is , it doesnt do partial search , for this feature to be usefull it sould match all subdomains belonging to a domain . Otherwise i dont see the point of exactly matching the subdomain  .


So -d domain.com , should match sub1.domain.com , test.domain.com and everything with domain.com (*.domain.com)  to be useful. 

also would be nice if stars are stripped from results.

**Comment by edoardottt** [comment]
Hi @kleozzy ! Thank you so much for spotting this.

Pushed a commit in `devel` branch (https://github.com/edoardottt/csprecon/compare/main...devel). It seems fixed now. 
 
Let me know

**Comment by kleozzy** [comment]
thanks for the quick fix, works fine for fecthing all matching subdomains.
Getting rid of the * in wildcard ones would make it perfect .

**Comment by edoardottt** [comment]
I chose to don't get rid of the wildcards because can be useful for piping those results with other tools while doing recon. It can be easily removed with `sed`.

I'll drop a new release now :)
